- name: Setup Erlang repo
  ansible.builtin.shell:  curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash


- name: Install RabbitMQ Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash


- name: Install Erlang and RabbitMQ
  ansible.builtin.yum:
    name:
      - rabbitmq-server
      - erlang
    state: installed


- name: start RabbitMQ service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes


- name: Add application user
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('amazon.aws.aws_ssm', ' {{env}}.{{component}}.amqp_user', region='us-east-1') }}"
    password: "{{ lookup('amazon.aws.aws_ssm', ' {{env}}.{{component}}.amqp_pass', region='us-east-1') }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present






